### ISSUE TITLE
Incorrect operator precedence in GetPointsOfInterest?

### ISSUE THREAD

**Issue by pcbbc** [mcaddy/audipoi#1]
Looks to be a very useful tool for when my new car arrives.  Thank you.

However I was just browsing your codebase, when I noticed the following SQL Select in method Mcaddy.AudiPoiDatabase.PointOfInterestDatabase.GetPointsOfInterest:
SELECT latmin + (latmax - latmin / 2) as lat, lonmin + (lonmax - lonmin / 2) as lon, city, street, housenr, name FROM poicoord JOIN poidata ON poicoord.poiid = poidata.poiid JOIN poiname on poiname.docid = poicoord.poiid WHERE type = @category

Surely that bracketing is incorrect, unless SQLite operator precedence is totally non-standard?!  Or have I missed something?

Should those first two selects not read "latmin + (latmax - latmin) / 2" and "lonmin + (lonmax - lonmin) / 2" instead?

**Comment by mcaddy** [comment]
Pull request merged, sorry for the delay.
