### ISSUE TITLE
No Update Found - 2020 A5 model F5F - Touch MMI

### ISSUE THREAD

**Issue by KevWal** [mcaddy/audipoi#11]
Hi

I have just purchased a 2020 A5 model F5F with the Touch MMI, and it doesn't seem to recognise the files created by audipoi - nor poibase, even though I have tried many different Fat32 formatted sticks.  :(    A couple of them have access LED's on, which blink away, but the software quickly comes back saying no update found.

Without a way to generate POI's online anymore, not sure how we find out what the file format should look like?

If I can help at all with more info or testing please let me know!

Thanks very much
Kevin

**Comment by mcaddy** [comment]
Not sure where to take this, I read elsewhere that the format has changed, if you find a way to generate POIs, leave a response on this ticket

**Comment by mcaddy** [comment]
@KevWal Did you find a solution?

**Comment by KevWal** [comment]
I did not, it doesn't seen to be possible anymore. .

**Comment by mcaddy** [comment]
@KevWal - Ok, will close this ticket
