### ISSUE TITLE
Uploaded to Cloud?

### ISSUE THREAD

**Issue by MaFtX** [mcaddy/audipoi#16]
Why does the database need uploading to the cloud servers? What purpose does this serve and what do you use the PGPSW data for?

**Comment by mcaddy** [comment]
It doesn't do anything anymore as the azure storage it was writing to has been terminated some time ago.

It started out as a bit of a debug tool as some users were reporting malformed databases, I grabbed a few to take a look, never did get to the bottom of the problem as the ones that I logged all seemed fine.

I lost interest in the project some time ago as my car Infotainment was not behaving and the ability to add up-to-date POIs was no longer a priority
