### ISSUE TITLE
Unable to find download link at PocketGPSworld.com, Please report error 1000 to developer

### ISSUE THREAD

**Issue by ghost** [mcaddy/audipoi#3]
When trying to download the maps it is failing

// Check to see the download link exisits, failing this check is the first indicator
// that someting has changed on the PocketGpsWorld website
if (!loggedInPage.Contains("<a href=\"/modules.php?name=Cameras\" class=\"sidemenu\">Download Speed Cams</a>"))
{
throw new WebException("Unable to find download link at PocketGPSworld.com, Please report error 1000 to developer");
}

**Comment by mcaddy** [comment]
Just had a look into this, I was fearing they had changed things significantly over at PocketGPSWorld.com. Luckily they've just forced HTTPS, so after updating the URLs all is now working fine again.

I've added a new binary v0.9.1 to the releases section.

**Comment by greggers1988** [comment]
Hi Mcaddy

it looks like this issue is occuring again, I have the same problem.

thanks

**Comment by ghost** [comment]
We've had some major server issues these last few days. It's been an absolute ballache to resolve to be honest. 

Can you give this a try again? The downloads on the site should be working as normal and I believe this is the method you use. 

Happy to discuss with the developer via email if any extra information is required - maft@ pock......

It will, however, be lower priority than being the rest of the site fully functional!!

MaFt - PocketGPSWorld
