### ISSUE TITLE
Audi error - The update data are not compatible or are outdated

### ISSUE THREAD

**Issue by andyshez** [mcaddy/audipoi#4]
Hi McAddy, firstly thank you for developing this app.

However, I'm getting the above error on my MMI (brand new S4 Avant) and I'm wondering if you can assist.

I am using your app to download from pocketgps and convert straight onto an SD card. I am not altering the files at all... Are you aware of any reason why I'd be getting this error?

Thanks

Andy

**Comment by mcaddy** [comment]
They might have changed the encoding, I've no easy way to test it beyond my own car. If you could generate a poi sd card the 'official way', zip up the contents and e-mail it over i can take a look.

**Comment by andyshez** [comment]
Thanks, I would love to, but that part of Audi Connect is down at the moment.

When/if it comes back online I will certainly send you a sample file.

Thank you for getting back to me.

Regards

Andy

On 26 Jul 2018, at 19:45, mcaddy <notifications@github.com<mailto:notifications@github.com>> wrote:


They might have changed the encoding, I've no easy way to test it beyond my own car. If you could generate a poi sd card the 'official way', zip up the contents and e-mail it over i can take a look.

**Comment by G66str6** [comment]
Hi mcaddy,
Can I be of any help providing you with a zip file of a POIBASE build?
You can add a max 5 poi categories for free and build a working sd card for the MMI running software version 1177.
kr

**Comment by mcaddy** [comment]
@G66str6 Yes, that might be useful.
